name: Find Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install tree command
      run: |
        command -v tree ||\
          sudo apt update -y
          sudo apt install tree -y
    - name: Print File Structure
      run: tree build
